services:
  - type: web
    name: memory-palace-builder 
    env: php
    plan: free 
    region: oregon
    rootDir: memory-palace-builder
    buildCommand: |
      composer install
      npm install
      npm run build
      php artisan migrate --force # Runs migrations on every build
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_URL
        value: https://automated-memory-palace-builder.onrender.com 
      - key: APP_KEY
        fromService:
          type: web
          name: memory-palace-builder
          envVarKey: APP_KEY
      - key: DATABASE_URL
        fromDatabase:
          name: memory-palace-db
          property: internalConnectionString

databases:
  - name: memory-palace-db
    plan: free
    region: oregon