services:
  - type: web
    name: memory-palace-app
    plan: free
    region: oregon
    env: docker
    dockerfilePath: ./Dockerfile
    
    startCommand: |
      php artisan migrate:fresh --seed --force &&
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      apache2-foreground

    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://memory-palace-app.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: memory-palace-db
          property: internalConnectionString
      - key: CACHE_DRIVER
        value: file 
      - key: SESSION_DRIVER
        value: file 

databases:
  - name: memory-palace-db
    plan: free
    region: oregon